package hackerrank;

public class GameofStones {
  static String gameOfStones(int n) {
    //P1, P2 두 명의 플레이어가 N개의 돌로 게임을 한다.
    //한 플레이어가 한 번 움직일때, 2,3,5개의 돌을 게임판에서 제거할수있다.
    //더이상 움직일 수 없다면 해당 플레이어가 지는 게임이다. 이때의 승자를 출력하는 문제
    
    return ( n % 7 > 1) ? "First" : "Second";
  }

  public static void main(String[] args) {
    //n%7한 결과가 7의 배수마다 반복되는 것을 알 수 있다.
    System.out.println(gameOfStones(1)+", ans: Second"); //0.142...
    System.out.println(gameOfStones(2)+", ans: First"); //0.285...
    System.out.println(gameOfStones(3)+", ans: First"); //0.428...
    System.out.println(gameOfStones(4)+", ans: First"); //0.571...
    System.out.println(gameOfStones(5)+", ans: First"); //0.714...
    System.out.println(gameOfStones(6)+", ans: First"); //0.857...
    System.out.println(gameOfStones(7)+", ans: Second"); //0
    System.out.println(gameOfStones(8)+", ans: Second"); //1.142...
    System.out.println(gameOfStones(9)+", ans: First"); //1.285...
    System.out.println(gameOfStones(10)+", ans: First"); //1.428...
    System.out.println(gameOfStones(13)+", ans: First"); //1.857...
    System.out.println(gameOfStones(14)+", ans: Second"); //2


  }
}
